# Generated by Django 4.2.10 on 2024-07-19 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
    ]
